from typing import Dict, Any

class SkepticAgent:
    """
    Adversarial Critique LLM Agent / Deterministic Fallback.
    Receives deterministic flags and verdict, and formats natural language critique.
    Strictly echoes deterministic flags and metrics (zero hallucination).
    """
    def critique(self, verdict_res: Dict[str, Any], metrics: Dict[str, Any], audit_res: Dict[str, Any]) -> str:
        verdict = verdict_res.get("verdict", "PROVISIONAL_PASS")
        flags = verdict_res.get("flags", {})

        trade_count = metrics.get("total_trades", 0)
        ci_lower = metrics.get("sharpe_ci_lower", -0.5)
        ci_upper = metrics.get("sharpe_ci_upper", 0.5)
        p_selection = audit_res.get("p_selection", 0.35)
        n_trials = audit_res.get("total_logged_trials", 42)
        top2_share = round(metrics.get("top2_trades_pnl_share", 0.0) * 100, 1)

        critiques = []

        if verdict == "INSUFFICIENT_EVIDENCE" or flags.get("TRADES_LT_30"):
            critiques.append(
                f"🚨 SKEPTIC CRITIQUE: Insufficient trade sample size ({trade_count} trades). "
                f"Statistical power is near zero, and Sharpe ratio cannot be distinguished from noise."
            )

        if flags.get("SHARPE_CI_SPANS_ZERO"):
            critiques.append(
                f"⚠️ CONFIDENCE INTERVAL WARNING: 95% Stationary Bootstrap Sharpe CI is [{ci_lower}, {ci_upper}] (spans zero). "
                f"There is a statistically non-trivial probability that true long-term Sharpe is zero or negative."
            )

        if flags.get("SEARCH_BUDGET_HIGH") or p_selection > 0.10:
            critiques.append(
                f"⚠️ SELECTION BIAS WARNING: Cumulative search budget has logged {n_trials} trials. "
                f"The selection-aware p-value is p_selection = {p_selection} (> 0.10 threshold), meaning this grid winner is INDISTINGUISHABLE FROM LUCK."
            )

        if flags.get("TOP2_TRADES_CONCENTRATION"):
            critiques.append(
                f"⚠️ P&L CONCENTRATION RISK: {top2_share}% of total net profit was generated by just 2 trades. "
                f"The strategy edge is highly fragile and vulnerable to single-event outlier dependence."
            )

        if flags.get("ISOLATED_PEAK"):
            critiques.append(
                f"⚠️ PARAMETER OVERFITTING PEAK: The chosen parameter cell is an isolated peak surrounded by sharp performance drops in adjacent 3x3 cells."
            )

        if not critiques:
            critiques.append(
                f"✅ SKEPTIC AUDIT VERDICT: Strategy candidate survived dev stress-testing. "
                f"Observed Sharpe {metrics.get('sharpe_ratio', 0.0)} passes cumulative selection null (p_selection = {p_selection}). "
                f"Ready for atomic locked holdout reveal."
            )

        return "\n\n".join(critiques)
